services:
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/database"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./desafio-tekna
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./desafio-tekna:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NG_CLI_ANALYTICS=ci
    command: npm start

volumes:
  postgres_data: