services:
  api:
    build:
      context: ./ 
      dockerfile: ./Dockerfile 
    ports:
      - "3000:3000" 
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/database" 
    volumes:
      - ./:/app 
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../desafio-tekna
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200" 
    volumes:
      - ../desafio-tekna:/app 
    stdin_open: true
    tty: true
    command: sh -c "npm install && npx ng serve --host 0.0.0.0"

volumes:
  postgres_data: